# Generated by Django 5.1.2 on 2024-10-10 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='item',
            name='inventory_i_created_a8d6f3_idx',
        ),
        migrations.RemoveIndex(
            model_name='item',
            name='inventory_i_updated_52dea4_idx',
        ),
    ]
