# Generated by Django 5.1.2 on 2024-10-09 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='authenticat_mobile__6dd7ca_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mobile_number',
        ),
    ]
