# Generated by Django 5.1.2 on 2024-10-09 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_user_authenticat_mobile__6dd7ca_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
